// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDg-U3siwzyGg2d0k34SrI41GDc1zbSSRE",
      authDomain: "speakeasy-bb246.firebaseapp.com",
      projectId: "speakeasy-bb246",
      storageBucket: "speakeasy-bb246.appspot.com",
      messagingSenderId: "532548607087",
      appId: "1:532548607087:web:cb676fe2d429855355019a",
      measurementId: "G-4ZVGW8ZLJB");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDlN0_F_EVgffykCtRbg-HId9_e98EWZRk",
    appId: '1:532548607087:android:c006717803dbf21055019a',
    messagingSenderId: "532548607087",
    projectId: "speakeasy-bb246",
    storageBucket: "speakeasy-bb246.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpVL9e2rdmwpmjmbMeNEpbo7GrxfnkJQg',
    appId: '1:564875037088:ios:082ad80b0097b45f2abcc5',
    messagingSenderId: '532548607087',
    projectId: 'medical-reminder-app-8ce9e',
    storageBucket: 'speakeasy-bb246.appspot.com',
    iosBundleId: 'com.example.languageLearningAssistant',
  );
}
